version: '3'

services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=twitter-oauth2
      - POSTGRES_USER=postgres
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432